#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

typedef enum {TRUE, FALSE} bool;
typedef enum {OK,ERR_FILE_NOT_FOUND, ERR_FILE_NOT_PERM, IMPOSSIBLE_VALID_BOARD, ERR_NOT_ENOUGH_MEMORY, ERR_WRONG_DIM, ERROR} code;

#endif